<a href="https://colab.research.google.com/github/Bahodir011/Bahodir011/blob/main/vazifalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
arr0 = np.array(np.arange(9))
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr = np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr1 = np.arange(12)
arr1
data = np.size(arr1)
data

12

In [11]:
arr2 = np.arange(10)
arr2
data2 = np.info(arr2)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x389e1d0
byteorder:  little
byteswap:  False
type: int64


In [12]:
vect = np.zeros(13)
vect[6] = 1
vect

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [13]:
vect1 = np.arange(20,60)
vect1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

In [15]:
vect2 = np.arange(-30,-5)
vect2

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6])

In [18]:
mat = np.arange(12,21).reshape(3,3)
mat


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [21]:
mat1 = [3,7,0,0,9,0]
info = np.nonzero(mat1)
info

(array([0, 1, 4]),)

In [22]:
# 10 ta vazifa tamomlandi

In [28]:
mass = np.random.randn(2,2)
mass

array([[ 0.02081996,  0.13519588],
       [-0.46031217,  1.16608542]])

In [37]:
mass1 = np.arange(81).reshape(9,9)
mass1
maxmass = np.max(mass1)
minmass = np.min(mass1)
maxmass
minmass

0

In [39]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

In [49]:
mat63 = np.arange(0,18).reshape(6,3)
mat34 = np.arange(0,12).reshape(3,4)

ma = np.dot(mat63, mat34)

ma

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [53]:
arra = np.arange(3)
arrb = np.arange(3,6)


In [55]:
arra > arrb

array([False, False, False])

In [56]:
arra >= arrb

array([False, False, False])

In [57]:
arra < arrb 

array([ True,  True,  True])

In [58]:
arra <= arrb

array([ True,  True,  True])

In [59]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-59-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-59-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

In [64]:
massive = np.array([2,3,4,5,6,7,8])
massive1 = np.array([5,3,78,9,0,6,88])
intersection = intersect1d(massive, massive1)
intersection

array([3, 5, 6])

In [67]:
tasodif = np.random.randn(6,2)
ts = np.trunc(tasodif)
ts

array([[ 1.,  0.],
       [ 1.,  1.],
       [ 0., -0.],
       [ 0., -0.],
       [-0.,  1.],
       [-0., -0.]])

In [ ]:
#20 mashq tugadi!!!!!

In [63]:
# 21 mashq
sorting = np.random.randn(10)
sorts = np.sort(sorting)
sorts

array([-1.50037972, -1.05933434, -0.64674539, -0.26078061, -0.05673674,
        0.08134636,  0.3522591 ,  0.54816074,  1.0433008 ,  1.51578473])

In [87]:
#22 mashq                        Chala
a = np.random.randn(4)
b = np.random.randn(4)

teng = np.array_equal(a, b)
teng

False

In [ ]:
#23 mashq
#Yuqorida bajarilgan ekan

In [89]:
#24 mashq
arg = np.random.randn(5)
arg
te = np.argmax(arg, axis = None)
te

2

In [91]:
#25 mashq
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [92]:
#26 va 27 mashq tayyrolangan


In [95]:
#28 mashq
import datetime
today = datetime.datetime.now().date()
yesterday = today - datetime.timedelta(days =1)
tomorrow = today + datetime.timedelta(days =1)

today, yesterday, tomorrow

(datetime.date(2023, 2, 11),
 datetime.date(2023, 2, 10),
 datetime.date(2023, 2, 12))

In [ ]:
#29 mashq


In [96]:
#30 mash ham tayyorlangan

In [97]:
#31 mashq ham tayyorlangan

In [98]:
#32 ham tayyorlangan

In [100]:
#33 shart
f = np.arange(20)
k = np.add.reduce(f)
k

190

In [3]:
#34 mashq tayyorlangan

In [5]:
#35 mash
ar = np.array([1, 2, 3, 4, 5])
result = ar * 100
result

array([100, 200, 300, 400, 500])

In [11]:
#36 mashq
q = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
t = np.lib.stride_tricks.as_strided(q, shape=(12,3), strides=(4,4))
t

array([[          1,  8589934592,           2],
       [ 8589934592,           2, 12884901888],
       [          2, 12884901888,           3],
       [12884901888,           3, 17179869184],
       [          3, 17179869184,           4],
       [17179869184,           4, 21474836480],
       [          4, 21474836480,           5],
       [21474836480,           5, 25769803776],
       [          5, 25769803776,           6],
       [25769803776,           6, 30064771072],
       [          6, 30064771072,           7],
       [30064771072,           7, 34359738368]])

In [ ]:
#37 mashq
